AllomorphSolution/Allomorph/Controllers/FolderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Allomorph.Models;
using PagedList;
using System.IO;
using Allomorph.Repositories;

namespace Allomorph.Controllers
{
    public class FolderController : Controller
    {
        // Database access layer
        private FolderRepository repo = new FolderRepository();

        // ~/Folder/Index == Yfirlit texta
        public ViewResult Index(SearchViewModel svm)
        {
            string sortOrder = svm.sortOrder;
            string currentFilter = svm.currentFilter;
            string searchString = svm.searchString;
            int? page = svm.page;
            int category = svm.ID;
            
            // Til að flokka eftir nafni á texta eða dagsetningunni sem hann var sendur inn
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            // Alltaf sýna síðu 1 ef það er notað leitina
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var folders = repo.GetAllFolders();

            // Ef það er leitað eftir flokki
            switch (category)
            {
                case 1:
                    folders = folders.Where(f => f.CategoryID == 1);
                    break;
                case 2:
                    folders = folders.Where(f => f.CategoryID == 2);
                    break;
                case 3:
                    folders = folders.Where(f => f.CategoryID == 3);
                    break;
                case 4:
                    folders = folders.Where(f => f.CategoryID == 4);
                    break;
            }

            // Leitað eftir nafni á möppu
            if (!String.IsNullOrEmpty(searchString))
            {
                folders = folders.Where(s => s.FolderName.ToUpper().Contains(searchString.ToUpper()));
            }

            // Flokka eftir nafni eða dagsetningu
            switch (sortOrder)
            {
                case "name_desc":
                    folders = folders.OrderByDescending(s => s.FolderName);
                    break;
                case "date_desc":
                    folders = folders.OrderByDescending(s => s.DateCreated);
                    break;
                case "date_asc":
                    folders = folders.OrderBy(s => s.DateCreated);
                    break;
                default:  // Name ascending 
                    folders = folders.OrderBy(s => s.FolderName);
                    break;
            }

            // Birtir 25 texta á hverri síðu
            int pageSize = 10;
            // pageNumber er sjálfgefið 1 ef engin síða er valin
            int pageNumber = (page ?? 1);
            return View(folders.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Folder/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Folder folder = repo.GetFolderById(id);
            if (folder == null)
            {
                return View("NotFound");
            }

            SubFile subtitle = repo.GetSubFileById(folder.ID);
            IEnumerable<Comment> comment = repo.GetCommentsById(folder.ID);

            return View(Tuple.Create(folder, subtitle, comment));
        }

        // GET: /Folder/Create
        [Authorize]
        public ActionResult Create(int? requestID)
        {
            ViewBag.request = repo.GetRequestById(requestID);
            ViewBag.requestId = requestID;
            return View(new Folder());
        }

        // POST: /Folder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CategoryID,FolderName,Link,Poster,Description")] Folder folder, HttpPostedFileBase file, SubFile subfile, int? requestID)
        {
            if (ModelState.IsValid)
            {
                // Nær í skráarendinguna á textaskránni
                string extension = Path.GetExtension(file.FileName);
                // Athugar hvort skráin sé á löglegu formi (.srt ending)
                if (extension != ".srt")
                {
                    return View("WrongFile");
                }
                // Geymir gögnin úr textaskránni sem er send inn
                StreamReader streamReader = new StreamReader(file.InputStream);

                // Tengja textaskrána við möppu og gefa henni nafn
                subfile.FolderID = folder.ID;
                subfile.SubName = file.FileName;
                // Setja möppuna og textaskrána í gagnagrunninn
                repo.AddFolder(folder);
                repo.AddSubFile(subfile);

                // .Peek() skoðar næsta tákn án þess að taka það úr strauminum
                // -1 Þegar öll skráin hefur verið lesin
                while (streamReader.Peek() != -1)
                {
                    string lineNumber = streamReader.ReadLine();
                    string timeLine = streamReader.ReadLine();

                    string firstTime = timeLine.Substring(0, 12);
                    string secondTime = timeLine.Substring(17);

                    string text = streamReader.ReadLine();
                    string nextline = streamReader.ReadLine();

                    // Til að ná öllum textalínum (þ.e. línur sem innihalda lesin texta)
                    while (nextline != "")
                    {
                        if (nextline == null)
                        {
                            break;
                        }
                        text += "\n" + nextline;
                        nextline = streamReader.ReadLine();
                    }

                    // Tekur inn allar upplýsingar fyrir línumódelið
                    SubFileLine tempLine = new SubFileLine()
                    {
                        SubFileID = subfile.ID,
                        LineNumber = Convert.ToInt32(lineNumber), 
                        StartTime = firstTime, 
                        EndTime = secondTime
                    }; 

                    // Tengja línurnar við textana (þýðingarnar)
                    SubFileLineTranslation tempTranslation = new SubFileLineTranslation()
                    {
                        SubFileLineID = tempLine.ID,
                        LineText = text,
                        LanguageID = subfile.LanguageID
                    };
                    SubFileLineTranslation trans = new SubFileLineTranslation()
                    {
                        SubFileLineID = tempLine.ID,
                        LineText = "",
                        LanguageID = 2
                    };
                    if (subfile.LanguageID == 2) {
                        trans.LanguageID = 1;
                    };
                    
                    // Setja textann í gagnagrunninn og vista breytingarnar
                    repo.AddLines(tempLine, tempTranslation, trans);
                    repo.Save();
                }
                // requestID != null ef verið er að uppfylla beiðni
                if (requestID != null)
                {
                    // Ná í beiðni úr gagnagrunni
                    var req = repo.GetRequestById(requestID);
                    // Villumeðhöndlun
                    if (req != null)
                    {
                        // Eyða beiðni úr gagnagrunni og vista breytingar
                        repo.RemoveRequest(req);
                        repo.Save();
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                return RedirectToAction("Details", new { id = folder.ID });
            }
            return View(folder);
        }

        // GET: /Folder/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            //Folder folder = repo.GetFolderById(id);
            Folder folder = repo.GetFolderById(id);
            if (folder == null)
            {
                return View("NotFound");
            }
            return View(folder);
        }

        // POST: /Folder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CategoryID,FolderName,Link,Poster,Description,DateCreated")] Folder folder)
        {
            if (ModelState.IsValid)
            {
                repo.Entry(folder);
                repo.Save();
                return RedirectToAction("Details", new { id = folder.ID });
            }
            return View(folder);
        }

        // GET: /Folder/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Folder folder = repo.GetFolderById(id);
            if (folder == null)
            {
                return View("NotFound");
            }
            return View(folder);
        }

        // POST: /Folder/Delete/5
        [HttpPost, ActionName("Delete")]

AllomorphSolution/Allomorph/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Allomorph.Models;
using PagedList;
using Allomorph.Repositories;

namespace Allomorph.Controllers
{
    public class RequestController : Controller
    {
        // Database access layer
        private FolderRepository repo = new FolderRepository();

        // GET: /Request/
        public ViewResult Index(SearchViewModel svm)
        {
            string sortOrder = svm.sortOrder;
            string currentFilter = svm.currentFilter;
            string searchString = svm.searchString;
            int? page = svm.page;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.VoteSortParm = String.IsNullOrEmpty(sortOrder) ? "vote_asc" : "";
            ViewBag.NameSortParm = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewBag.DateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var req = repo.GetAllRequests();

            if (!String.IsNullOrEmpty(searchString))
            {
                req = req.Where(r => (r.RequestName.ToUpper().Contains(searchString.ToUpper()) || r.RequestText.ToUpper().Contains(searchString.ToUpper())));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    req = req.OrderByDescending(s => s.RequestName);
                    break;
                case "date_desc":
                    req = req.OrderByDescending(s => s.DateCreated);
                    break;
                case "date_asc":
                    req = req.OrderBy(s => s.DateCreated);
                    break;
                case "name_asc":
                    req = req.OrderBy(s => s.RequestName);
                    break;
                case "vote_asc":
                    req = req.OrderBy(s => s.ReqUpvoteCounter);
                    break;
                default:  // Votes descending
                    req = req.OrderByDescending(s => s.ReqUpvoteCounter);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(req.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        [ValidateInput(false)]
        public ActionResult RequestVote(int requestID)
        {
            // Fetch current users UserName
            string usr = System.Web.HttpContext.Current.User.Identity.Name;

            // reqLike is a list of all the likes associated with this request
            var reqLike = repo.GetAllLikes(requestID);

            if (reqLike != null)
            {
                // Loop to check if the current user has already liked this request
                foreach (var like in reqLike)
                {
                    if (like.LikeUserName == usr)
                    {
                        return RedirectToAction("Index");
                    }
                }

            }
            // Create the like and add it to the database
            Like newLike = new Like() { RequestID = requestID, LikeUserName = usr };
            repo.AddLike(newLike);

            // Find the request
            Request request = repo.GetRequestById(requestID);
            if (request == null)
            {
                return View("NotFound");
            }
            // Add 1 to it's vote counter and save the changes
            request.ReqUpvoteCounter += 1;
            repo.Save();
            return RedirectToAction("Index");
        }

        // GET: /Request/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Request request = repo.GetRequestById(id);
            if (request == null)
            {
                return View("NotFound");
            }
            return View(request);
        }

        // GET: /Request/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,UserName,RequestName,RequestText")] Request request)
        {
            if (ModelState.IsValid)
            {
                string usr = System.Web.HttpContext.Current.User.Identity.Name;
                if (usr != null)
                {
                    request.UserName = usr;
                }
                repo.AddRequest(request);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View(request);
        }

        // GET: /Request/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Request request = repo.GetRequestById(id);
            if (request == null)
            {
                return View("NotFound");
            }
            return View(request);
        }

        // POST: /Request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RequestName,RequestText,ReqUpvoteCounter,DateCreated")] Request request)
        {
            if (ModelState.IsValid)
            {
                repo.Entry(request);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View(request);
        }

        // GET: /Request/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            Request request = repo.GetRequestById(id);
            if (request == null)
            {
                return View("NotFound");
            }
            return View(request);
        }

        // POST: /Request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Request request = repo.GetRequestById(id);
            repo.RemoveRequest(request);
            repo.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AllomorphSolution/Allomorph/Views/Request/Create.cshtml
@model Allomorph.Models.Request

@{
    ViewBag.Title = "Beiðnir";
}

<h3>Senda inn beiðni</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal createForm">
        <br />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.RequestName, "Nafn á myndefni:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestName)
                @Html.ValidationMessageFor(model => model.RequestName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestText, "Lýsing á beiðni:", new { @class = "control-label col-md-2" })
            <div class="col-md-10 textAreaFor">
                @Html.TextAreaFor(model => model.RequestText, 4, 30, new { @class = "foo" })
                @Html.ValidationMessageFor(model => model.RequestText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Búa til" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <input type="submit" value="Til baka í beiðnir" class="btn btn-default btn-primary" onclick="location.href='@Url.Action("Index", "Request")'" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AllomorphSolution/Allomorph/Views/Request/Delete.cshtml
@model Allomorph.Models.Request

@{
    ViewBag.Title = "Eyða beiðni";
}

<h3>Eyða beiðni @Model.RequestName</h3>

<h4>Ertu viss um að þú viljir eyða þessu?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReqUpvoteCounter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReqUpvoteCounter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-success" /> |
            <input type="button" value="Til baka í beiðnir" class="btn btn-default btn-primary" onclick="location.href='@Url.Action("Index", "Request")'" />
        </div>
    }
</div>

AllomorphSolution/Allomorph/Views/Request/Details.cshtml
@model Allomorph.Models.Request

@{
    ViewBag.Title = "Upplýsingar um beiðni";
}

<h3>@Model.RequestName</h3>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.LabelFor(model => model.RequestName, "Nafn á myndefni:", new { @class = "control-label col-md-2" })
        </dt>

        <dd>
            @Html.ActionLink(Model.RequestName, "Create", "Folder", new { requestID = Model.ID }, null)
        </dd>

        <dt>
            @Html.LabelFor(model => model.RequestText, "Lýsing á myndefni:", new { @class = "control-label col-md-2" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestText)
        </dd>

        <dt>
            @Html.LabelFor(model => model.ReqUpvoteCounter, "Atkvæði:", new { @class = "control-label col-md-2" })
        </dt>

        <dd>
            <a href="@Url.Action("RequestVote", "Request", new { requestID = Model.ID })">
                <span id="voteReqBtn" class="glyphicon glyphicon-thumbs-up"></span>
            </a>
            @Html.DisplayFor(model => model.ReqUpvoteCounter)
        </dd>

        <dt>
            @Html.LabelFor(model => model.DateCreated, "Dagsetning:", new { @class = "control-label col-md-2" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>
</div>
<div>
    <input type="submit" value="Breyta" class="btn btn-default btn-success" onclick="location.href='@Url.Action("Edit", "Request", new { id = Model.ID })'" /> |
    <input type="submit" value="Til baka í beiðnir" class="btn btn-default btn-primary" onclick="location.href='@Url.Action("Index", "Request")'" />
</div>

AllomorphSolution/Allomorph/Views/Request/Edit.cshtml
@model Allomorph.Models.Request

@{
    ViewBag.Title = "Breyta beiðni";
}

<h3>Breyta beiðni @Model.RequestName</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.ReqUpvoteCounter)
        @Html.HiddenFor(model => model.DateCreated)

        <div class="form-group">
            @Html.LabelFor(model => model.RequestName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestName)
                @Html.ValidationMessageFor(model => model.RequestName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestText, new { @class = "control-label col-md-2" })
            <div class="col-md-10 textAreaFor">
                @Html.TextAreaFor(model => model.RequestText, 4, 30, new { @class = "foo" })
                @Html.ValidationMessageFor(model => model.RequestText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <input type="submit" value="Til baka í beiðnir" class="btn btn-default btn-primary" onclick="location.href='@Url.Action("Index", "Request")'" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AllomorphSolution/Allomorph/Views/Request/Index.cshtml
@model PagedList.IPagedList<Allomorph.Models.Request>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Beiðnir";
}

@{ Html.RenderPartial("Search", new Allomorph.Models.Folder()); }

<h3>Beiðnir</h3>

<div id="btnBuaTilBeidni">
    <input type="submit" value="Búa til nýja beiðni" class="btn btn-default btn-lg btn-success" onclick="location.href='@Url.Action("Create", "Request")'" />
</div>

@using (Html.BeginForm("Index", "Request", FormMethod.Get))
{      
    <div role="search">
        <div class="form-group" id="leitFormBeidnir">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "  Leita í beiðnum..." })
        </div>
        <button id="btnLeitBeidnir" class="btn btn-default" type="submit">Leita!</button>
    </div>
}

<table class="table table-condensed table-bordered">
    <tr class="active">
        <th class="indexNrReq">
            Nr.
        </th>
        <th class="requestTable">
            <span class="glyphicon glyphicon-sort-by-alphabet"></span>
            @Html.ActionLink("Nafn", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th class="requestTable">
            @Html.ActionLink("Lýsing", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th class="indexVotes">
            <span class="glyphicon glyphicon-sort"></span>
            @Html.ActionLink("Atkvæði", "Index", new { sortOrder = ViewBag.VoteSortParm })
        </th>
        <th class="indexDateReq">
            <span class="glyphicon glyphicon-sort"></span>
            @Html.ActionLink("Sett inn", "Index", new { sortOrder = ViewBag.DateSortParm })
        </th>
        <th class="indexEditDeleteReq"></th>
    </tr>
    @{ int i = 1; }
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{ var nr = Model.PageNumber - 1; }
                @if (Model.PageNumber != 1)
                {
                    if (i == 10)
                    {
                        i = 0;
                        nr += 1;
                    }@nr
                }@i
            </td>
            <td>
                @Html.ActionLink(item.RequestName, "Create", "Folder", new { requestID = item.ID }, null)
            </td>
            <td id="reqTextColumn">
                @Html.DisplayFor(modelItem => item.RequestText)
            </td>
            <td id="reqVoteColumn">
                <a href="@Url.Action("RequestVote", "Request", new { requestID = item.ID })">
                    <span id="voteReqBtn" class="glyphicon glyphicon-thumbs-up"></span>
                </a>
                @Html.DisplayFor(modelItem => item.ReqUpvoteCounter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.ActionLink("Breyta", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Eyða", "Delete", new { id = item.ID })
            </td>
        </tr>
                i++;
    }
</table>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))